<?php

namespace panix\engine\maintenance\controllers;

use Yii;
use yii\web\Controller;

/**
 * Default controller of maintenance mode
 *
 * @see \yii\web\Controller
 */
class MaintenanceController extends Controller
{
    public $title;
    public $message;
    public $viewPath;

    /**
     * Initialize controller.
     */
    public function init()
    {
        $this->setViewPath(__DIR__.'/../views/maintenance');
        $this->layout = Yii::$app->maintenanceMode->layoutPath;
        $this->title = ($this->title) ? $this->title : Yii::$app->maintenanceMode->title;
        $this->message = ($this->message) ? $this->message : Yii::$app->maintenanceMode->message;
       // $this->viewPath = ($this->viewPath) ? $this->viewPath : Yii::$app->maintenanceMode->viewPath;
        parent::init();


    }

    public function beforeAction($action)
    {
        if (Yii::$app->getRequest()->getIsAjax()) {
            return false;
        }
       // echo Yii::getAlias('@maintenance');

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Index action.
     * @return bool|string
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'title' => $this->title,
            'message' => $this->message
        ]);
    }



    /**
     * Index action.
     * @param string $message
     * @return bool|string
     */
    public function actionExpired($message)
    {
        return $this->render('expired', [
            'message' => $message
        ]);
    }


    public function actionBanned($message)
    {
        return $this->render('banned', [
            'message' => $message,
            'time'=> Yii::$app->user->banTime
        ]);
    }
} 